# This is a basic workflow to help you get started with Actions

name: FirebaseDeploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    branches: [ master ]
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set node Version
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: install firebase & pnpm
        run: npm i -g firebase-tools pnpm

      - name: install modules
        run: pnpm i

      - name: Bot send message
        uses: ./.github/actions/tg-bot-message
        with:
          message: Deploy started.
          token: ${{ secrets.TELEGRAM_TOKEN }}

      - name: build
        run: pnpm build

      - name: Get last commit message
        id: git_message
        uses: ./.github/actions/github-commit-message

      - name: Deploy
        run: firebase deploy --token $TOKEN -m "${{ steps.git_message.outputs.last_commit_message }}"
        env:
          TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Bot send message
        uses: ./.github/actions/tg-bot-message
        with:
          message: ${{ format('Deployed! "{0}" view at {1}', steps.git_message.outputs.last_commit_message, 'https://admin-logs-3ffc8.web.app/') }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
